apiVersion: v1
kind: Service
metadata:
  name: info-reader
  namespace: applications
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: info-reader

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-reader
  namespace: applications
spec:
  replicas: 3
  selector:
    matchLabels:
      app: info-reader
  template:
    metadata:
      labels:
        app: info-reader
    spec:
      containers:
      - env:
          - name: host 
            valueFrom: 
              configMapKeyRef: 
                key: host
                name: cassandra-configmap
          - name: pass 
            valueFrom: 
              configMapKeyRef: 
                key: pass
                name: cassandra-configmap
        name: info-reader
        image: diana1996/info-reader:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /.well-known/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /.well-known/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 8080
        
